# Site settings
title: blog of a toy
email: 
description: "Toy programs"
baseurl: ""
url: "http://ybcs.github.io"
twitter_username: karpathy
github_username:  ybcs

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge